import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./sidebar/SideNav";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  icons: {icon: "https://i.ibb.co/FXJ2RL7/Screenshot-2024-01-10-104130-1.png"},
  title: "Task Buddy",
  description: "Generated by Ahmed Hossain",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <div className="flex h-screen">
      <div className="w-2/12 bg-gray-100">
      <SideNav></SideNav>
      </div>
      <div className="w-10/12">
        <div className="h-[15%] w-full  bg-gray-100 border">
          <h3 className="text-xl font-semibold text-end py-2 text-[#00AAFF]">lorem</h3>
        </div>
        <div className="h-[85%] w-full bg-gray-50">
        {children}
        </div>
      </div>
    </div>

      </body>
    </html>
  );
}